//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MAFRANFER_WPF
{
    using System;
    using System.Collections.Generic;
    
    public partial class profesor
    {
        public int profesor_id { get; set; }
        public string nro_documento { get; set; }
        public string tipo_documento { get; set; }
        public string nombre { get; set; }
        public string apellido { get; set; }
        public string direccion { get; set; }
        public string celular { get; set; }
        public string telefono { get; set; }
        public string email { get; set; }
        public string sexo { get; set; }
        public System.DateTime fecha_nacimiento { get; set; }
        public string titulo { get; set; }
        public string observacion { get; set; }
    }
}
